/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-10-14 09:35:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("    <META http-equiv=Content-Type CONTENT=\"text/html; charset=gbk\" />\r\n");
      out.write("\t<TITLE>Itcast OA</TITLE>\r\n");
      out.write("\t<LINK HREF=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/blue/login.css\" type=text/css rel=stylesheet />\r\n");
      out.write("</HEAD>\r\n");
      out.write("\r\n");
      out.write("<BODY LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0 CLASS=PageBody >\r\n");
      out.write("\r\n");
      out.write("\r\n");

	
	//WebApplicationContext ctx = (WebApplicationContext)application.getAttribute(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE);
	//out.print(ctx + "<br/>");
	//out.print(WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE);
	//ctx = WebApplicationContextUtils.getWebApplicationContext(application);
	//out.print("<br/>"+ctx);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<FORM METHOD=\"post\" NAME=\"actForm\" ACTION=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/userAction_login.action\">\r\n");
      out.write("    <DIV ID=\"CenterAreaBg\">\r\n");
      out.write("        <DIV ID=\"CenterArea\">\r\n");
      out.write("            <DIV ID=\"LogoImg\"><IMG BORDER=\"0\" SRC=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/blue/images/logo.png\" /></DIV>\r\n");
      out.write("            <DIV ID=\"LoginInfo\">\r\n");
      out.write("                <TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 width=100%>\r\n");
      out.write("                \t <TR>\r\n");
      out.write("                        <TD width=45 CLASS=\"Subject\" colspan=\"3\">\r\n");
      out.write("                        \t<font color=\"red\">\r\n");
      out.write("\t                        \t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                        \t</font>\r\n");
      out.write("                        </TD>\r\n");
      out.write("                    </TR>\r\n");
      out.write("                    <TR>\r\n");
      out.write("                        <TD width=45 CLASS=\"Subject\"><IMG BORDER=\"0\" SRC=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/blue/images/login/userId.gif\" /></TD>\r\n");
      out.write("                        <TD><INPUT id=\"loginName\" SIZE=\"20\" CLASS=\"TextField\" TYPE=\"text\" NAME=\"loginName\" /></TD>\r\n");
      out.write("                        <TD ROWSPAN=\"2\" STYLE=\"padding-left:10px;\"><INPUT TYPE=\"image\" SRC=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/blue/images/login/userLogin_button.gif\"/></TD>\r\n");
      out.write("                    </TR>\r\n");
      out.write("                    <TR>\r\n");
      out.write("                        <TD CLASS=\"Subject\"><IMG BORDER=\"0\" SRC=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/style/blue/images/login/password.gif\" /></TD>\r\n");
      out.write("                        <TD><INPUT SIZE=\"20\" CLASS=\"TextField\" TYPE=\"password\" NAME=\"password\" /></TD>\r\n");
      out.write("                    </TR>\r\n");
      out.write("                </TABLE>\r\n");
      out.write("            </DIV>\r\n");
      out.write("            <DIV ID=\"CopyRight\"><A HREF=\"javascript:void(0)\">&copy; 2010 版权所有 itcast</A></DIV>\r\n");
      out.write("        </DIV>\r\n");
      out.write("    </DIV>\r\n");
      out.write("</FORM>\r\n");
      out.write("</BODY>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tdocument.getElementById('loginName').focus();\r\n");
      out.write("</script>\r\n");
      out.write("</HTML>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
