/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-28 12:51:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.base;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class staff_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- 导入jquery核心类库 -->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-1.8.3.js\"></script>\r\n");
      out.write("<!-- 导入easyui类库 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyui/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyui/themes/icon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyui/ext/portal.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/default.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyui/ext/jquery.portal.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyui/ext/jquery.cookie.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/easyui/locale/easyui-lang-zh_CN.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction doAdd() {\r\n");
      out.write("\t\t//alert(\"增加...\");\r\n");
      out.write("\t\t$('#addStaffWindow').window(\"open\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction doView() {\r\n");
      out.write("\t\talert(\"查看...\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction doDelete() {\r\n");
      out.write("\t\t//获取数据表格中所有选中的行，返回数组对象\r\n");
      out.write("\r\n");
      out.write("\t\tvar rows = $(\"#grid\").datagrid(\"getSelections\");\r\n");
      out.write("\r\n");
      out.write("\t\tif (rows.length == 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//没哟选中记录时，弹出提示\r\n");
      out.write("\t\t\t$.messager.alert(\"提示信息\", \"请选择要删除的记录！\", \"warning\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t//选中了取派员弹出确认框\r\n");
      out.write("\t\t\t$.messager\r\n");
      out.write("\t\t\t\t\t.confirm(\r\n");
      out.write("\t\t\t\t\t\t\t\"提示信息\",\r\n");
      out.write("\t\t\t\t\t\t\t\"确定要删除所选项吗？？\",\r\n");
      out.write("\t\t\t\t\t\t\tfunction(r) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (r) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar array = new Array();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//确定，发送请求\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//获取所选取派员的ID\r\n");
      out.write("\t\t\t\t\t\t\t\t\tfor (var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar staff = rows[i];\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar id = staff.id;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tarray.push(id);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar ids = array.join(\",\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tlocation.href = \"staffAction_deleteBatch.action?ids=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ ids;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction doRestore() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar rows = $(\"#grid\").datagrid(\"getSelections\");\r\n");
      out.write("\r\n");
      out.write("\t\tif (rows.length == 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t//没哟选中记录时，弹出提示\r\n");
      out.write("\t\t\t$.messager.alert(\"提示信息\", \"请选择要还原的记录！\", \"warning\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t//选中了取派员弹出确认框\r\n");
      out.write("\t\t\t$.messager.confirm(\"提示信息\", \"确定要还原所选项吗？？\", function(r) {\r\n");
      out.write("\t\t\t\tif (r) {\r\n");
      out.write("\t\t\t\t\tvar array = new Array();\r\n");
      out.write("\t\t\t\t\t//确定，发送请求\r\n");
      out.write("\t\t\t\t\t//获取所选取派员的ID\r\n");
      out.write("\t\t\t\t\tfor (var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tvar staff = rows[i];\r\n");
      out.write("\t\t\t\t\t\tvar id = staff.id;\r\n");
      out.write("\t\t\t\t\t\tarray.push(id);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar ids = array.join(\",\");\r\n");
      out.write("\t\t\t\t\tlocation.href = \"staffAction_recoverBatch.action?ids=\"\r\n");
      out.write("\t\t\t\t\t\t\t+ ids;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t//工具栏\r\n");
      out.write("\tvar toolbar = [ {\r\n");
      out.write("\t\tid : 'button-view',\r\n");
      out.write("\t\ttext : '查询',\r\n");
      out.write("\t\ticonCls : 'icon-search',\r\n");
      out.write("\t\thandler : doView\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tid : 'button-add',\r\n");
      out.write("\t\ttext : '增加',\r\n");
      out.write("\t\ticonCls : 'icon-add',\r\n");
      out.write("\t\thandler : doAdd\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tid : 'button-delete',\r\n");
      out.write("\t\ttext : '作废',\r\n");
      out.write("\t\ticonCls : 'icon-cancel',\r\n");
      out.write("\t\thandler : doDelete\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tid : 'button-save',\r\n");
      out.write("\t\ttext : '还原',\r\n");
      out.write("\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\thandler : doRestore\r\n");
      out.write("\t} ];\r\n");
      out.write("\t// 定义列\r\n");
      out.write("\tvar columns = [ [ {\r\n");
      out.write("\t\tfield : 'id',\r\n");
      out.write("\t\tcheckbox : true,\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tfield : 'name',\r\n");
      out.write("\t\ttitle : '姓名',\r\n");
      out.write("\t\twidth : 120,\r\n");
      out.write("\t\talign : 'center'\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tfield : 'telephone',\r\n");
      out.write("\t\ttitle : '手机号',\r\n");
      out.write("\t\twidth : 120,\r\n");
      out.write("\t\talign : 'center'\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tfield : 'haspda',\r\n");
      out.write("\t\ttitle : '是否有PDA',\r\n");
      out.write("\t\twidth : 120,\r\n");
      out.write("\t\talign : 'center',\r\n");
      out.write("\t\tformatter : function(data, row, index) {\r\n");
      out.write("\t\t\tif (data == \"1\") {\r\n");
      out.write("\t\t\t\treturn \"有\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn \"无\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tfield : 'deltag',\r\n");
      out.write("\t\ttitle : '是否作废',\r\n");
      out.write("\t\twidth : 120,\r\n");
      out.write("\t\talign : 'center',\r\n");
      out.write("\t\tformatter : function(data, row, index) {\r\n");
      out.write("\t\t\tif (data == \"0\") {\r\n");
      out.write("\t\t\t\treturn \"正常使用\"\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn \"已作废\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tfield : 'standard',\r\n");
      out.write("\t\ttitle : '取派标准',\r\n");
      out.write("\t\twidth : 120,\r\n");
      out.write("\t\talign : 'center'\r\n");
      out.write("\t}, {\r\n");
      out.write("\t\tfield : 'station',\r\n");
      out.write("\t\ttitle : '所属单位',\r\n");
      out.write("\t\twidth : 200,\r\n");
      out.write("\t\talign : 'center'\r\n");
      out.write("\t} ] ];\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t// 先将body隐藏，再显示，不会出现页面刷新效果\r\n");
      out.write("\t\t$(\"body\").css({\r\n");
      out.write("\t\t\tvisibility : \"visible\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 取派员信息表格\r\n");
      out.write("\t\t$('#grid').datagrid({\r\n");
      out.write("\t\t\ticonCls : 'icon-forward',\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\trownumbers : true,\r\n");
      out.write("\t\t\tstriped : true,\r\n");
      out.write("\t\t\tpageList : [ 30, 50, 100 ],\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\ttoolbar : toolbar,\r\n");
      out.write("\t\t\turl : \"staffAction_pageQuery.action\",\r\n");
      out.write("\t\t\tidField : 'id',\r\n");
      out.write("\t\t\tcolumns : columns,\r\n");
      out.write("\t\t\tonDblClickRow : doDblClickRow\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// 添加取派员窗口\r\n");
      out.write("\t\t$('#addStaffWindow').window({\r\n");
      out.write("\t\t\ttitle : '添加取派员',\r\n");
      out.write("\t\t\twidth : 400,\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tshadow : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\theight : 400,\r\n");
      out.write("\t\t\tresizable : false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// 修改取派员窗口\r\n");
      out.write("\t\t$('#editStaffWindow').window({\r\n");
      out.write("\t\t\ttitle : '修改取派员',\r\n");
      out.write("\t\t\twidth : 400,\r\n");
      out.write("\t\t\tmodal : true,\r\n");
      out.write("\t\t\tshadow : true,\r\n");
      out.write("\t\t\tclosed : true,\r\n");
      out.write("\t\t\theight : 400,\r\n");
      out.write("\t\t\tresizable : false\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction doDblClickRow(rowIndex, rowData) {\r\n");
      out.write("\r\n");
      out.write("\t\t//打开取派员窗口\r\n");
      out.write("\r\n");
      out.write("\t\t$('#editStaffWindow').window(\"open\");\r\n");
      out.write("\t\t//使用form表单对象的load方法回显数据\r\n");
      out.write("\t\t$(\"#editStaffForm\").form(\"load\", rowData);\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\" style=\"visibility: hidden;\">\r\n");
      out.write("\t<div region=\"center\" border=\"false\">\r\n");
      out.write("\t\t<table id=\"grid\"></table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"easyui-window\" title=\"对收派员进行添加或者修改\" id=\"addStaffWindow\"\r\n");
      out.write("\t\tcollapsible=\"false\" minimizable=\"false\" maximizable=\"false\"\r\n");
      out.write("\t\tstyle=\"top: 20px; left: 200px\">\r\n");
      out.write("\t\t<div region=\"north\" style=\"height: 31px; overflow: hidden;\"\r\n");
      out.write("\t\t\tsplit=\"false\" border=\"false\">\r\n");
      out.write("\t\t\t<div class=\"datagrid-toolbar\">\r\n");
      out.write("\t\t\t\t<a id=\"save\" icon=\"icon-save\" href=\"#\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\tplain=\"true\">保存</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div region=\"center\" style=\"overflow: auto; padding: 5px;\"\r\n");
      out.write("\t\t\tborder=\"false\">\r\n");
      out.write("\t\t\t<form id=\"addStaffForm\" action=\"staffAction_add.action\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"table-edit\" width=\"80%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">收派员信息</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- TODO 这里完善收派员添加 table -->\r\n");
      out.write("\t\t\t\t\t<!-- \t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>取派员编号</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"id\" class=\"easyui-validatebox\" required=\"true\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>姓名</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"name\" class=\"easyui-validatebox\"\r\n");
      out.write("\t\t\t\t\t\t\trequired=\"true\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>手机</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 扩展手机号校验规则 --> <script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t//表单校验\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#save\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar v = $(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#addStaffForm\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.form(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"validate\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (v) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#addStaffForm\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.submit();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar reg = /^1[3|4|5|7|8][0-9]{9}$/;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.extend($.fn.validatebox.defaults.rules, {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttelephone : {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalidator : function(value, param) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treturn reg.test(value);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tmessage : '手机号输入有误'\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t</script> <input type=\"text\" data-options=\"validType:'telephone'\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"telephone\" class=\"easyui-validatebox\" required=\"true\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>单位</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"station\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-validatebox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"><input type=\"checkbox\" name=\"haspda\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"1\" /> 是否有PDA</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>取派标准</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"standard\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-validatebox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 修改取派员窗口 -->\r\n");
      out.write("\t<div class=\"easyui-window\" title=\"对收派员进行添加或者修改\" id=\"editStaffWindow\"\r\n");
      out.write("\t\tcollapsible=\"false\" minimizable=\"false\" maximizable=\"false\"\r\n");
      out.write("\t\tstyle=\"top: 20px; left: 200px\">\r\n");
      out.write("\t\t<div region=\"north\" style=\"height: 31px; overflow: hidden;\"\r\n");
      out.write("\t\t\tsplit=\"false\" border=\"false\">\r\n");
      out.write("\t\t\t<div class=\"datagrid-toolbar\">\r\n");
      out.write("\t\t\t\t<a id=\"edit\" icon=\"icon-edit\" href=\"#\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\tplain=\"true\">保存</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div region=\"center\" style=\"overflow: auto; padding: 5px;\"\r\n");
      out.write("\t\t\tborder=\"false\">\r\n");
      out.write("\t\t\t<form id=\"editStaffForm\" action=\"staffAction_edit.action\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"id\">\r\n");
      out.write("\t\t\t\t<table class=\"table-edit\" width=\"80%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">收派员信息</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>姓名</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"name\" class=\"easyui-validatebox\"\r\n");
      out.write("\t\t\t\t\t\t\trequired=\"true\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>手机</td>\r\n");
      out.write("\t\t\t\t\t\t<td><script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t$(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t//为保存按钮绑定事件\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#edit\").click(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//表单校验，如果通过，提交表单\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar v = $(\"#editStaffForm\").form(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"validate\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (v) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//$(\"#addStaffForm\").form(\"submit\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"#editStaffForm\").submit();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tvar reg = /^1[3|4|5|7|8][0-9]{9}$/;\r\n");
      out.write("\t\t\t\t\t\t\t\t//扩展手机号校验规则\r\n");
      out.write("\t\t\t\t\t\t\t\t$.extend($.fn.validatebox.defaults.rules, {\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttelephone : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalidator : function(value, param) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn reg.test(value);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmessage : '手机号输入有误！'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script> <input type=\"text\" data-options=\"validType:'telephone'\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"telephone\" class=\"easyui-validatebox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>单位</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"station\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-validatebox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"><input type=\"checkbox\" name=\"haspda\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"1\" /> 是否有PDA</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>取派标准</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"standard\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-validatebox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
